//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReflectiveCode.GMinder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReflectiveCode.GMinder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What.
        /// </summary>
        internal static string AgendaColumnWhat {
            get {
                return ResourceManager.GetString("AgendaColumnWhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When.
        /// </summary>
        internal static string AgendaColumnWhen {
            get {
                return ResourceManager.GetString("AgendaColumnWhen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Days.
        /// </summary>
        internal static string AgendaGroupDays {
            get {
                return ResourceManager.GetString("AgendaGroupDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Months.
        /// </summary>
        internal static string AgendaGroupMonths {
            get {
                return ResourceManager.GetString("AgendaGroupMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Month.
        /// </summary>
        internal static string AgendaGroupNextMonth {
            get {
                return ResourceManager.GetString("AgendaGroupNextMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Week.
        /// </summary>
        internal static string AgendaGroupNextWeek {
            get {
                return ResourceManager.GetString("AgendaGroupNextWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past.
        /// </summary>
        internal static string AgendaGroupPast {
            get {
                return ResourceManager.GetString("AgendaGroupPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string AgendaGroupToday {
            get {
                return ResourceManager.GetString("AgendaGroupToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomorrow.
        /// </summary>
        internal static string AgendaGroupTomorrow {
            get {
                return ResourceManager.GetString("AgendaGroupTomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Weeks.
        /// </summary>
        internal static string AgendaGroupWeeks {
            get {
                return ResourceManager.GetString("AgendaGroupWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not access your Google Calendar account. Make sure you accept when asked to authorize GMinder..
        /// </summary>
        internal static string ErrorAccessGoogleCalendarText {
            get {
                return ResourceManager.GetString("ErrorAccessGoogleCalendarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t access Google Calendar account.
        /// </summary>
        internal static string ErrorAccessGoogleCalendarTitle {
            get {
                return ResourceManager.GetString("ErrorAccessGoogleCalendarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding event.
        ///You may not have permission to edit the selected calendar..
        /// </summary>
        internal static string ErrorAddingEvent {
            get {
                return ResourceManager.GetString("ErrorAddingEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load saved calendars and events.
        /// </summary>
        internal static string ErrorCalendarEventsLoad {
            get {
                return ResourceManager.GetString("ErrorCalendarEventsLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save calendars and events.
        /// </summary>
        internal static string ErrorCalendarEventsSave {
            get {
                return ResourceManager.GetString("ErrorCalendarEventsSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error downloading calendars
        ///Did you Accept GMinder&apos;s access to your Google Calendar account?
        ///Are you connected to the internet?.
        /// </summary>
        internal static string ErrorDownloadCalendars {
            get {
                return ResourceManager.GetString("ErrorDownloadCalendars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception in GMinder.
        /// </summary>
        internal static string ErrorGenericExceptionTitle {
            get {
                return ResourceManager.GetString("ErrorGenericExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must first click on the Login button to allow GMinder access to your Google Calendar.
        /// </summary>
        internal static string ErrorLoginFirstText {
            get {
                return ResourceManager.GetString("ErrorLoginFirstText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login First.
        /// </summary>
        internal static string ErrorLoginFirstTitle {
            get {
                return ResourceManager.GetString("ErrorLoginFirstTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link {0} could not be opened!.
        /// </summary>
        internal static string ErrorOpenLink {
            get {
                return ResourceManager.GetString("ErrorOpenLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error playing audio file: {0}
        ///Please go to Options and select a valid sound file..
        /// </summary>
        internal static string ErrorSoundPlay {
            get {
                return ResourceManager.GetString("ErrorSoundPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Error:.
        /// </summary>
        internal static string ErrorUnknown {
            get {
                return ResourceManager.GetString("ErrorUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Unknown Error is occured. Please feel free to inform Developer!.
        /// </summary>
        internal static string ErrorUnknownMain {
            get {
                return ResourceManager.GetString("ErrorUnknownMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No event selected.
        /// </summary>
        internal static string EventNotSelectedText {
            get {
                return ResourceManager.GetString("EventNotSelectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Event first!.
        /// </summary>
        internal static string EventNotSelectedToolTip {
            get {
                return ResourceManager.GetString("EventNotSelectedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://maps.google.com/maps?q={0}.
        /// </summary>
        internal static string GoogleMapsLink {
            get {
                return ResourceManager.GetString("GoogleMapsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snooze until {0} minutes before start.
        /// </summary>
        internal static string MenuItemSnoozeText {
            get {
                return ResourceManager.GetString("MenuItemSnoozeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account information has been set. Click Download to import your calendars..
        /// </summary>
        internal static string MessageLoginSuccessText {
            get {
                return ResourceManager.GetString("MessageLoginSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string MessageLoginSuccessTitle {
            get {
                return ResourceManager.GetString("MessageLoginSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A web browser will now be opened to allow you to accept giving GMinder access to your Calendar..
        /// </summary>
        internal static string MessageLoginText {
            get {
                return ResourceManager.GetString("MessageLoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string MessageLoginTitle {
            get {
                return ResourceManager.GetString("MessageLoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !.
        /// </summary>
        internal static string PersonStateAccepted {
            get {
                return ResourceManager.GetString("PersonStateAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string PersonStateDeclined {
            get {
                return ResourceManager.GetString("PersonStateDeclined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PersonStateNeedsAction {
            get {
                return ResourceManager.GetString("PersonStateNeedsAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string PersonStateTentative {
            get {
                return ResourceManager.GetString("PersonStateTentative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string PersonToString {
            get {
                return ResourceManager.GetString("PersonToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} [{2}].
        /// </summary>
        internal static string PersonToStringState {
            get {
                return ResourceManager.GetString("PersonToStringState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All day.
        /// </summary>
        internal static string sAllDay {
            get {
                return ResourceManager.GetString("sAllDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendee.
        /// </summary>
        internal static string sAttendee {
            get {
                return ResourceManager.GetString("sAttendee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendee Optional.
        /// </summary>
        internal static string sAttendeeOptional {
            get {
                return ResourceManager.GetString("sAttendeeOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendees.
        /// </summary>
        internal static string sAttendees {
            get {
                return ResourceManager.GetString("sAttendees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sAttendees Optional.
        /// </summary>
        internal static string sAttendeesOptional {
            get {
                return ResourceManager.GetString("sAttendeesOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        internal static string sCalendar {
            get {
                return ResourceManager.GetString("sCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string sDescription {
            get {
                return ResourceManager.GetString("sDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string sDownload {
            get {
                return ResourceManager.GetString("sDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        internal static string sDownloading {
            get {
                return ResourceManager.GetString("sDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string sLocation {
            get {
                return ResourceManager.GetString("sLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string sLogin {
            get {
                return ResourceManager.GetString("sLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizer.
        /// </summary>
        internal static string sOrganizer {
            get {
                return ResourceManager.GetString("sOrganizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Login.
        /// </summary>
        internal static string sResetLogin {
            get {
                return ResourceManager.GetString("sResetLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        internal static string sResources {
            get {
                return ResourceManager.GetString("sResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        internal static string UnitDay {
            get {
                return ResourceManager.GetString("UnitDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        internal static string UnitDays {
            get {
                return ResourceManager.GetString("UnitDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hr.
        /// </summary>
        internal static string UnitHour {
            get {
                return ResourceManager.GetString("UnitHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        internal static string UnitMinute {
            get {
                return ResourceManager.GetString("UnitMinute", resourceCulture);
            }
        }
    }
}
